### PR TITLE
ft: create error handler method

### LINKED ISSUE #63: Add a method to set the error handler
The main advantage of this will be chaining of operations.

Currently, we have to do this:

```r
app <- Ambiorix$new()
# ...
app$error <- error_handler
app$start()
```

This is the desired suggestion:

```r
app <- Ambiorix$
  new()$
  set_error_handler(error_handler)$
  ...

app$start()
```

### PR DESCRIPTION
**Pull request by kennedymwavu**
Add a method to set the error handler

Closes #63

### CODE REVIEW

**Comment by JohnCoene** [comment]
Do you mind `set_error` instead of `set_error_handler` that would make it more consistent with other methods (e.g.: `set_404` ~`set_404_handler`~).

Also maybe check that the `handler` is indeed a function (there is an {assertthat} function for that somewhere in the package.

**Comment by kennedymwavu** [comment]
Very sensible. Making the suggested changes.

**Comment by kennedymwavu** [comment]
Don't merge yet... Let me make one more change: Use `all()` instead of `&&` for backward compatibility.

**Comment by kennedymwavu** [comment]
LGTM now.

**Comment by JohnCoene** [comment]
Thanks!

**Pull request merged**
